[theme]
primaryColor="#0066cc"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f0f8ff"
textColor="#262730"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
